2nd code review
im-tollu/yandex-go-musthave-shortener-tpl pull request #6
Opened 2021-10-02 14:20 UTC by im-tollu

2021-10-03 18:37 UTC, iTiky requested changes
1. Слишком много panic в местах, где функция должна вернуть ошибку. Явно паниковать - это анти-паттерн Go.
2. В некоторых местах к ошибке добавляется контекст (`fmt.Errorf`), в других она прокидывается "as is". Второго стоит избегать.
3. Отсутствуют godoc-комментарии. Тяжело читать такой код, т.к. необходимо изучить тело функции, чтобы понять что она делает.
4. "Всё в одной куче". Нет изоляции слоёв приложения (отделение бизнес-логики от API и storage). Это же касается и тестов. Ниже моё предложение по расположению частей кода в Go-приложении.

```
/cmd/main.go - точка входа
/api - API слой приложения
    /handler - все handler-ы
    /model - API модели
    /middleware - MW
/model - каконичные модели
/service - уровень бизнес-логики приложения
    /shortener - один из сервисов приложения
        interface.go - интерфейс сервиса
        /v1 - имплементация сервиса
/storage - уровень БД приложения
    interface.go - storage интерфейсы
        /inmem - in-memory DB реализация
        /psql - PostgreSQL
            model.go - модели специфичные для psql
        /mock - мок-имплементация
```
storage используется как зависимость для service.
service используется как зависимость для API.
API используются главной функцией main.
Если есть какие-то вопросы, на них можно попытаться ответить на 1-2-1.

2021-10-03 18:37 UTC, iTiky commented on cmd/shortener/main.go
> +		panic(err)
Паника в Go это исключительный случай. Завершать (даже критически) приложение через панику - это плохой паттерн. Я бы посоветовал `log.Fatalf`, так сохраняется паттерн логирования.

2021-10-03 18:37 UTC, iTiky commented on internal/app/config.go
> +	errConf := env.Parse(&conf)
Лучше придерживаться стандартного подхода к оформлению Go-кода:
```go
if err := someFunc(); err != nil {
    // do somethin
}
```
Одна строка экономии, но +5 к читабельности.

2021-10-03 18:37 UTC, iTiky commented on internal/app/config.go
> +		panic(errConf)
Если что-то пошло не так с функцией, она должна вернуть ошибку, но не паниковать. Решение о панике может принимать только слой ответственный за время жизни приложения.

2021-10-03 18:37 UTC, iTiky commented on internal/app/config.go
> +	if baseURLStr > "" {
В первый раз такое вижу. Я бы советовал более привычный вариант:
```go
if str != "" {
    //
}
```

2021-10-03 18:37 UTC, iTiky commented on internal/app/config.go
> +			panic(errParse)
Если пользователю отдать стек-трейс паники, вряд ли он поймет что конкретно он не так сконфигурировал. Необходимо давать больше контекста пользователю.

2021-10-03 18:37 UTC, iTiky commented on internal/app/config.go
> +	if baseURLStr > "" {
Кажется. что если baseURLStr не задан, приложение не будет корректно работать.

2021-10-03 18:37 UTC, iTiky commented on internal/app/config.go
> +func LoadConfig() Config {
1. Из трёх параметров функция валидирует только один. Это означает, что приложение может запуститься с неверной конфигурацией.
2. Валидацию конфига стоит отделять от создания конфига, т.е. лучше задать две функции `NewConfig()` и `func (cfg Config) Validate() error`.

2021-10-03 18:37 UTC, iTiky commented on internal/app/server.go
> +type URLShortener struct {
В одном файле описаны две сущности с конструкторами и методами для каждого из них. Лучше разделить это на несколько файлов, иначе сложно воспринимать и поддерживать такой код.

2021-10-03 18:37 UTC, iTiky commented on internal/app/server.go
> +		panic(errBackup)
Функция возвращает ошибку. Почему бы не заменить панику на возврат ошибки?

2021-10-03 18:37 UTC, iTiky commented on internal/app/server.go
> +	return s.Server.ListenAndServe()
Чаще всего, для читабельности, `return` отделяют пустой строкой, т.к. мельком взглянув на код, сразу видны точки выхода функции.

2021-10-03 18:37 UTC, iTiky commented on internal/app/server.go
> +type LongURLJson struct {
Модели лучше вынести в отдельный файл `models.go`.  Обычно, поведение сервиса описывают интерфейсом, т.о. будет два файла `interface.go` и `models.go`. Такое оформление кода значительно упрощает его восприятие другими разработчиками.

2021-10-03 18:37 UTC, iTiky commented on internal/app/server.go
> +type URLShortener struct {
В дополнение. В одном файле собран API и service уровни, определены модели, middleware-ы.

2021-10-03 18:37 UTC, iTiky commented on internal/app/repository.go
> +	GetURLBy(id int) *url.URL
`GetURLBy`. By what? Когда много getter-ов, суффикс определяет доп. параметры. Более понятное имя функции - проще ею пользоваться. В данном случае `By(id)`, т.е. как бы логично, но обычно первый параметр - это контекст, что ломает такой нейминг.

2021-10-03 18:37 UTC, iTiky commented on internal/app/repository.go
> +func NewReader(fileName string) (*reader, error) {
`reader` - private тип, но для него задан public конструктор. Это анти-паттерн Go, т.к. можно создать "скрытый" тип извне, используя конструктор. Лучше скрывать имплементацию полностью.

2021-10-03 18:37 UTC, iTiky commented on internal/app/repository.go
> +func NewReader(fileName string) (*reader, error) {
Справедливо и для методов типа.

2021-10-03 18:37 UTC, iTiky commented on internal/app/repository.go
> +	file, err := os.OpenFile(fileName, os.O_RDONLY|os.O_CREATE, 0777)
777 ? Мало-мало overkill, т.к. этот файл точно не executable =)

2021-10-03 18:37 UTC, iTiky commented on internal/app/repository.go
> +package app
Смутило имя файла `repository`, т.к. я ожидал тут увидеть http репо, а это скорее `storage`. Я бы посоветовал добавить иерархии в директорию `/app`, т.к. сейчас всё в одной куче.

2021-10-03 18:37 UTC, iTiky commented on internal/app/server_test.go
>  type RepositoryMock struct {
Обычно моки генерируются через `go generate` и помещая их в файл с тестом, такой подход рушится (если интерфейс изменится, нужно править моки). Более того, если мок необходимо использовать в других тестах, его нужно будет определять и там. См. комментарий к PR, там я описал более или менее "правильное" (или часто-применяемое) расположение файлов в Go-проекте.

2021-10-03 18:37 UTC, iTiky commented on internal/app/server_test.go
> +func TestMain(m *testing.M) {
Этот тест должен лежать в `config_test.go`. Все тесты в одной куче сильно затрудняют поддержку кода.

2021-10-04 17:09 UTC, im-tollu commented on cmd/shortener/main.go
> +		panic(err)
Избавился от паник в коде, в пакете main применил log.Fatalf

2021-10-04 17:54 UTC, im-tollu commented on internal/app/config.go
> +	errConf := env.Parse(&conf)
Заменил все такие места, где вызов функции возвращает только ошибку.

2021-10-04 17:55 UTC, im-tollu commented on internal/app/config.go
> +		panic(errConf)
Исправил. Паник в коде больше не осталось.

2021-10-04 18:00 UTC, im-tollu commented on internal/app/config.go
> +	if baseURLStr > "" {
Неравенство исправил.

2021-10-05 17:04 UTC, im-tollu commented on internal/app/config.go
> +			panic(errParse)
Добавил baseURLStr к сообщению об ошибке

2021-10-06 17:28 UTC, im-tollu commented on internal/app/repository.go
> +	file, err := os.OpenFile(fileName, os.O_RDONLY|os.O_CREATE, 0777)
Сделал 444 для чтения и 222 для записи.

2021-10-06 17:29 UTC, im-tollu commented on internal/app/server_test.go
>  type RepositoryMock struct {
Моки пока что не пробовал генерировать. Пока что переместил в ./storage/mocks

2021-10-06 17:46 UTC, im-tollu commented on internal/app/repository.go
> +func NewReader(fileName string) (*reader, error) {
Сделал приватным.

2021-10-06 18:09 UTC, im-tollu commented on internal/app/server_test.go
> +func TestMain(m *testing.M) {
Убрал лишнее из тестов сервера.

2021-10-06 18:10 UTC, im-tollu commented on internal/app/repository.go
> +package app
Переехал в storage.

2021-10-06 18:15 UTC, im-tollu commented on internal/app/server.go
> +	return s.Server.ListenAndServe()
Отделил.

2021-10-06 18:32 UTC, im-tollu commented on internal/app/repository.go
> +	GetURLBy(id int) *url.URL
Переименовал GetURLBy -> GetByID

2021-10-06 18:33 UTC, im-tollu commented on internal/app/server.go
> +type URLShortener struct {
Разделено.

2021-10-06 20:10 UTC, im-tollu commented on internal/app/config.go
> +func LoadConfig() Config {
Валидации конфига не предполагалось вообще. Так получилось, поскольку нужно парсить URL. Но в свежей версии я применил `flag.Func()`.

2021-10-09 21:32 UTC, merged